package com.acme.autogenerated.model;

import lombok.Data;
import org.springframework.boot.context.properties.ConfigurationProperties;

@Data
@ConfigurationProperties("autogenerated.rootnode2")
public class RootNode2 {
  private String charlie;
  private int delta;
}
