package model;

import lombok.Data;
import org.springframework.boot.context.properties.ConfigurationProperties;

@Data
@ConfigurationProperties("autogenerated.rootnode2")
public class RootNode2 {
    /**
     * Charlie description
     */
    private String charlie;
    /**
     * Custom description
     */
    private int delta;
    /**
     * Enum description
     */
    private TopLevelEnum topLevelEnum;
}
