package com.acme.model;

import lombok.Data;
import org.springframework.boot.context.properties.ConfigurationProperties;

@Data
@ConfigurationProperties("autogenerated.rootnode2")
public class RootNode2 {
    /**
     * Charlie fresh comment
     */
    private String charlie;
    /**
     * Delta comment
     */
    private int delta;
    /**
     * Top level enum comment
     */
    private TopLevelEnum topLevelEnum;
}
