package com.acme.model;

import lombok.Data;
import org.springframework.boot.context.properties.ConfigurationProperties;

@Data
@ConfigurationProperties("autogenerated.rootnode1")
public class RootNode1 {
  private ChildNode childNode;
  private ChildNode11 childNode11;
  private ChildNode12 childNode12;
  private char[] charArrayProperty;
  private String stringProperty;
  private int intProperty;
  private double doubleProperty;
  private byte byteProperty;
  private Integer integerWrapperProperty;
  private Double doubleWrapperProperty;
  private Enum1 enumProperty;


  private enum Enum1 {
    val1, val2, val3
  }


  @Data
  private class ChildNode11 {
    private String childProperty11;
  }


  @Data
  private class ChildNode12 {
    private boolean childProperty12;
  }
}
