package com.acme.model;

import lombok.Data;
import org.springframework.boot.context.properties.ConfigurationProperties;

import java.util.Set;

@Data
@ConfigurationProperties("autogenerated.rootnode1")
public class RootNode1 {
    private ChildNode childNode;
    private ChildNode11 childNode11;
    private ChildNode12 childNode12;
    private char[] charArrayProperty;
    private String stringProperty;
    private int intProperty;
    private double doubleProperty;
    private byte byteProperty;
    private Integer integerWrapperProperty;
    private Double doubleWrapperProperty;
    private Enum1 enumProperty;
    private Enum2 anotherEnumProperty;
    private Set<Enum2> enumValues;


    public enum Enum1 {
        val1, val2, val3
    }

    public static enum Enum2 {
        val1, val2, val3
    }

    @Data
    private class ChildNode11 {
        private String childProperty11;
    }


    @Data
    private class ChildNode12 {
        private boolean childProperty12;
    }
}
