name: Java Gradle CI test

on: [push]

jobs:
  # Run Gradle Wrapper Validation Action to verify the wrapper's checksum
#  gradleValidation: ## Skipped till samples is updated/fixed
#    name: Gradle Wrapper
#    runs-on: ubuntu-latest
#    steps:
#
#      # Check out current repository
#      - name: Fetch Sources
#        uses: actions/checkout@v2.3.4
#
#      # Validate wrapper
#      - name: Gradle Wrapper Validation
#        uses: gradle/wrapper-validation-action@v1.0.3
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - uses: actions/checkout@v2

      # Cache Gradle dependencies
      - name: Setup Gradle Dependencies Cache
        uses: actions/cache@v2.1.5
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', 'gradle.properties') }}

      # Cache Gradle Wrapper
      - name: Setup Gradle Wrapper Cache
        uses: actions/cache@v2.1.5
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Clean
        run: ./gradlew clean


      - name: Test Plugin
        run: ./gradlew test

      - name: Build Plugin
        run: ./gradlew buildPlugin


      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: build/distributions
