# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Publish branch master to EAP channel

on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  build:
    environment: JetBrains Marketplace
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        cache: gradle

    - name: Build with Gradle
      run: gradle buildPlugin

    # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
    # the publishing section of your build.gradle
    - name: Publish to JetBrains Marketplace
      run: gradle publishPlugin
      env:
        PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        CERTIFICATE_CHAIN: ${{ secrets.CERTIFICATE_CHAIN }}
