name: Java Gradle CI test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
#      - name: Cache Maven packages #disable for now, may replace with https://github.com/burrunan/gradle-cache-action
#        uses: actions/cache@v2
#        with:
#          path: ~/.m2
#          key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml') }}
#          restore-keys: ${{ runner.os }}-m2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean buildPlugin
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: build/distributions
